name: 05 - 1 -event filters and sctivities types

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a pull requestis opened or sycronized and branch is main"

