# See 06-contexts/README.md for more information
# about the how to use contexts in GitHub Actions.

name: 06 - Contexts

on:
  push:
  workflow_dispatch:

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display information
        run: |
          echo "Event Names: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          echo "Variable value: ${{ vars.MY_VAR }}"

          
          

